=== viajovem/animal/json_schemas/Villager-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Villager schema",
        "description": "Data for a Villager",
        "default": {},
        "examples": [
            {
                "birthday": {
                    "month": 1,
                    "day": 27,
                    "text": "January 27th"
                },
                "species": "Bird",
                "name": "Admiral",
                "data_url": "https://nookipedia.com/wiki/Admiral",
                "personality": "Cranky",
                "gender": "Male",
                "zodiac": "Aquarius"
            },
            {
                "data_url": "https://nookipedia.com/wiki/Agent_S",
                "personality": "Peppy",
                "gender": "Female",
                "zodiac": "Cancer",
                "birthday": {
                    "text": "July 2nd",
                    "month": 7,
                    "day": 2
                },
                "species": "Squirrel",
                "name": "Agent S"
            },
            {
                "zodiac": "Taurus",
                "birthday": {
                    "month": 4,
                    "day": 21,
                    "text": "April 21st"
                },
                "species": "Pig",
                "name": "Agnes",
                "data_url": "https://nookipedia.com/wiki/Agnes",
                "personality": "Sisterly",
                "gender": "Female"
            }
        ],
        "additionalProperties": true,
        "required": [
            "name",
            "species",
            "personality",
            "gender",
            "birthday",
            "zodiac",
            "data_url"
        ],
        "properties": {
            "name": {
                "$id": "#/items/properties/name",
                "type": "string",
                "title": "The Name Schema",
                "description": "Villager name.",
                "default": "",
                "examples": [
                    "Admiral"
                ]
            },
            "species": {
                "$id": "#/items/properties/species",
                "type": "string",
                "title": "The Species Schema",
                "description": "Villager species.",
                "default": "",
                "examples": [
                    "Bird"
                ]
            },
            "personality": {
                "$id": "#/items/properties/personality",
                "type": "string",
                "title": "The Personality Schema",
                "description": "Villager personality type.",
                "default": "",
                "examples": [
                    "Cranky"
                ]
            },
            "gender": {
                "$id": "#/items/properties/gender",
                "type": "string",
                "title": "The Gender Schema",
                "description": "Villager's listed gender.",
                "default": "",
                "examples": [
                    "Male"
                ]
            },
            "birthday": {
                "$id": "#/items/properties/birthday",
                "type": "object",
                "title": "The Birthday Schema",
                "description": "Contains data for a villager's birthday.",
                "default": {},
                "examples": [
                    {
                        "month": 1,
                        "day": 27,
                        "text": "January 27th"
                    }
                ],
                "additionalProperties": true,
                "required": [
                    "month",
                    "day",
                    "text"
                ],
                "properties": {
                    "month": {
                        "$id": "#/items/properties/birthday/properties/month",
                        "type": "integer",
                        "title": "The Month Schema",
                        "description": "Integer representation of villager's birth month.",
                        "default": 0,
                        "examples": [
                            1
                        ]
                    },
                    "day": {
                        "$id": "#/items/properties/birthday/properties/day",
                        "type": "integer",
                        "title": "The Day Schema",
                        "description": "Integer representation of villager's birth day.",
                        "default": 0,
                        "examples": [
                            27
                        ]
                    },
                    "text": {
                        "$id": "#/items/properties/birthday/properties/text",
                        "type": "string",
                        "title": "The Text Schema",
                        "description": "String representation of villager's birthday.",
                        "default": "",
                        "examples": [
                            "January 27th"
                        ]
                    }
                }
            },
            "zodiac": {
                "$id": "#/items/properties/zodiac",
                "type": "string",
                "title": "The Zodiac Schema",
                "description": "Zodiac sign villager's birthday falls under.",
                "default": "",
                "examples": [
                    "Aquarius"
                ]
            },
            "data_url": {
                "$id": "#/items/properties/data_url",
                "type": "string",
                "title": "The Data_url Schema",
                "description": "url data was scrapped from.",
                "default": "",
                "examples": [
                    "https://nookipedia.com/wiki/Admiral"
                ]
            }
        }
    }
}

=== viajovem/animal/Villagers.json
[
    {
        "name": "Admiral",
        "species": "Bird",
        "personality": "Cranky",
        "gender": "Male",
        "birthday": {
            "month": 1,
            "day": 27,
            "text": "January 27th"
        },
        "zodiac": "Aquarius",
        "data_url": "https://nookipedia.com/wiki/Admiral"
    },
    {
        "name": "Agent S",
        "species": "Squirrel",
        "personality": "Peppy",
        "gender": "Female",
        "birthday": {
            "month": 7,
            "day": 2,
            "text": "July 2nd"
        },
        "zodiac": "Cancer",
        "data_url": "https://nookipedia.com/wiki/Agent_S"
    },
    {
        "name": "Agnes",
        "species": "Pig",
        "personality": "Sisterly",
        "gender": "Female",
        "birthday": {
            "month": 4,
            "day": 21,
            "text": "April 21st"
        },
        "zodiac": "Taurus",
        "data_url": "https://nookipedia.com/wiki/Agnes"
    },
    {
        "name": "Al",
        "species": "Gorilla",
        "personality": "Lazy",
        "gender": "Male",
        "birthday": {
            "month": 10,
            "day": 18,
            "text": "October 18th"
        },
        "zodiac": "Libra",
        "data_url": "https://nookipedia.com/wiki/Al"
    },
    {
        "name": "Alfonso",
        "species": "Alligator",
        "personality": "Lazy",
        "gender": "Male",
        "birthday": {
            "month": 6,
            "day": 9,
            "text": "June 9th"
        },
        "zodiac": "Gemini",
        "data_url": "https://nookipedia.com/wiki/Alfonso"
    },
    {
        "name": "Alice",
        "species": "Koala",
        "personality": "Normal",
        "gender": "Female",
        "birthday": {
            "month": 8,
            "day": 19,
            "text": "August 19th"
        },
        "zodiac": "Leo",
        "data_url": "https://nookipedia.com/wiki/Alice"
    },
    {
        "name": "Alli",
        "species": "Alligator",
        "personality": "Snooty",
        "gender": "Female",
        "birthday": {
            "month": 11,
            "day": 8,
            "text": "November 8th"
        },
        "zodiac": "Scorpio",
        "data_url": "https://nookipedia.com/wiki/Alli"
    },
    {
        "name": "Amelia",
        "species": "Eagle",
        "personality": "Snooty",
        "gender": "Female",
        "birthday": {
            "month": 11,
            "day": 19,
            "text": "November 19th"
        },
        "zodiac": "Scorpio",
        "data_url": "https://nookipedia.com/wiki/Amelia"
    },
    {
        "name": "Anabelle",
        "species": "Anteater",
        "personality": "Peppy",
        "gender": "Female",
        "birthday": {
            "month": 2,
            "day": 16,
            "text": "February 16"
        },
        "zodiac": "Aquarius",
        "data_url": "https://nookipedia.com/wiki/Anabelle"
    },
    {
        "name": "Anchovy",
        "species": "Bird",
        "personality": "Lazy",
        "gender": "Male",
        "birthday": {
            "month": 3,
            "day": 4,
            "text": "March 4th"
        },
        "zodiac": "Pisces",
        "data_url": "https://nookipedia.com/wiki/Anchovy"
    },
    {
        "name": "Angus",
        "species": "Bull",
        "personality": "Cranky",
        "gender": "Male",
        "birthday": {
            "month": 4,
            "day": 30,
            "text": "April 30th"
        },
        "zodiac": "Taurus",
        "data_url": "https://nookipedia.com/wiki/Angus"
    },
    {
        "name": "Anicotti",
        "species": "Mouse",
        "personality": "Peppy",
        "gender": "Female",
        "birthday": {
            "month": 2,
            "day": 24,
            "text": "February 24th"
        },
        "zodiac": "Pisces",
        "data_url": "https://nookipedia.com/wiki/Anicotti"
    },
    {
        "name": "Ankha",
        "species": "Cat",
        "personality": "Snooty",
        "gender": "Female",
        "birthday": {
            "month": 9,
            "day": 22,
            "text": "September 22nd"
        },
        "zodiac": "Virgo",
        "data_url": "https://nookipedia.com/wiki/Ankha"
    },
    {
        "name": "Annalisa",
        "species": "Anteater",
        "personality": "Normal",
        "gender": "Female",
        "birthday": {
            "month": 2,
            "day": 6,
            "text": "February 6"
        },
        "zodiac": "Aquarius",
        "data_url": "https://nookipedia.com/wiki/Annalisa"
    },
    {
        "name": "Annalise",
        "species": "Horse",
        "personality": "Snooty",
        "gender": "Female",
        "birthday": {
            "month": 12,
            "day": 2,
            "text": "December 2nd"
        },
        "zodiac": "Sagittarius",
        "data_url": "https://nookipedia.com/wiki/Annalise"
    },
    {
        "name": "Antonio",
        "species": "Anteater",
        "personality": "Jock",
        "gender": "Male",
        "birthday": {
            "month": 10,
            "day": 20,
            "text": "October 20"
        },
        "zodiac": "Libra",
        "data_url": "https://nookipedia.com/wiki/Antonio"
    },
    {
        "name": "Apollo",
        "species": "Eagle",
        "personality": "Cranky",
        "gender": "Male",
        "birthday": {
            "month": 7,
            "day": 4,
            "text": "July 4th"
        },
        "zodiac": "Cancer",
        "data_url": "https://nookipedia.com/wiki/Apollo"
    },
    {
        "name": "Apple",
        "species": "Hamster",
        "personality": "Peppy",
        "gender": "Female",
        "birthday": {
            "month": 9,
            "day": 24,
            "text": "September 24th"
        },
        "zodiac": "Libra",
        "data_url": "https://nookipedia.com/wiki/Apple"
    },
    {
        "name": "Astrid",
        "species": "Kangaroo",
        "personality": "Snooty",
        "gender": "Female",
        "birthday": {
            "month": 9,
            "day": 8,
            "text": "September 8th"
        },
        "zodiac": "Virgo",
        "data_url": "https://nookipedia.com/wiki/Astrid"
    },
    {
        "name": "Audie",
        "species": "Wolf",
        "personality": "Peppy",
        "gender": "Female",
        "birthday": {
            "month": 8,
            "day": 31,
            "text": "August 31st"
        },
        "zodiac": "Virgo",
        "data_url": "https://nookipedia.com/wiki/Audie"
    },
    {
        "name": "Aurora",
        "species": "Penguin",
        "personality": "Normal",
        "gender": "Female",
        "birthday": {
            "month": 1,
            "day": 27,
            "text": "January 27th"
        },
        "zodiac": "Aquarius",
        "data_url": "https://nookipedia.com/wiki/Aurora"
    },
    {
        "name": "Ava",
        "species": "Chicken",
        "personality": "Normal",
        "gender": "Female",
        "birthday": {
            "month": 4,
            "day": 28,
            "text": "April 28th"
        },
        "zodiac": "Taurus",
        "data_url": "https://nookipedia.com/wiki/Ava"
    },
    {
        "name": "Avery",
        "species": "Eagle",
        "personality": "Cranky",
        "gender": "Male",
        "birthday": {
            "month": 2,
            "day": 22,
            "text": "February 22nd"
        },
        "zodiac": "Pisces",
        "data_url": "https://nookipedia.com/wiki/Avery"
    },
    {
        "name": "Axel",
        "species": "Elephant",
        "personality": "Jock",
        "gender": "Male",
        "birthday": {
            "month": 3,
            "day": 23,
            "text": "March 23rd"
        },
        "zodiac": "Aries",
        "data_url": "https://nookipedia.com/wiki/Axel"
    },
    {
        "name": "Baabara",
        "species": "Sheep",
        "personality": "Snooty",
        "gender": "Female",
        "birthday": {
            "month": 3,
            "day": 28,
            "text": "March 28th"
        },
        "zodiac": "Aries",
        "data_url": "https://nookipedia.com/wiki/Baabara"
    },
    {
        "name": "Bam",
        "species": "Deer",
        "personality": "Jock",
        "gender": "Male",
        "birthday": {
            "month": 11,
            "day": 7,
            "text": "November 7th"
        },
        "zodiac": "Scorpio",
        "data_url": "https://nookipedia.com/wiki/Bam"
    },
    {
        "name": "Bangle",
        "species": "Tiger",
        "personality": "Peppy",
        "gender": "Female",
        "birthday": {
            "month": 8,
            "day": 27,
            "text": "August 27th"
        },
        "zodiac": "Virgo",
        "data_url": "https://nookipedia.com/wiki/Bangle"
    },
    {
        "name": "Barold",
        "species": "Cub",
        "personality": "Lazy",
        "gender": "Male",
        "birthday": {
            "month": 3,
            "day": 2,
            "text": "March 2nd"
        },
        "zodiac": "Pisces",
        "data_url": "https://nookipedia.com/wiki/Barold"
    },
    {
        "name": "Bea",
        "species": "Dog",
        "personality": "Normal",
        "gender": "Female",
        "birthday": {
            "month": 10,
            "day": 15,
            "text": "October 15th"
        },
        "zodiac": "Libra",
        "data_url": "https://nookipedia.com/wiki/Bea"
    },
    {
        "name": "Beardo",
        "species": "Bear",
        "personality": "Smug",
        "gender": "Male",
        "birthday": {
            "month": 9,
            "day": 27,
            "text": "September 27"
        },
        "zodiac": "Libra",
        "data_url": "https://nookipedia.com/wiki/Beardo"
    },
    {
        "name": "Beau",
        "species": "Deer",
        "personality": "Lazy",
        "gender": "Male",
        "birthday": {
            "month": 4,
            "day": 5,
            "text": "April 5th"
        },
